# Generated by Django 3.0.14 on 2021-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210603_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
